import {
  img1,
  img2,
  img3,
  img4,
  img5,
  img6,
  img7,
  img8,
  img9,
  img10,
  img11,
} from "./assets/images";

export const ProductList = [
  {
    _id: 1,
    name: "Salad",
    desc: "Fresh Tomatos and Spinach with colorful combination of veggies",
    amount: "$59",
    image: img1,
  },
  {
    _id: 2,
    name: "Pastry",
    desc: "Finely baked and served",
    amount: "$59",
    image: img2,
  },
  {
    _id: 3,
    name: "Hakka Noodles",
    desc: "Noodles with veggies finely chopped",
    amount: "$59",
    image: img3,
  },
  {
    _id: 4,
    name: "Fruit Salad",
    desc: "Kiwi, Raspberry, Lemon and more",
    amount: "$59",
    image: img4,
  },
  {
    _id: 5,
    name: "Pan Cakes",
    desc: "Refreshing and breath-taking",
    amount: "$59",
    image: img5,
  },
  {
    _id: 6,
    name: "Burgers",
    desc: "Spicy, tacky burgers with sauce",
    amount: "$59",
    image: img6,
  },
  {
    _id: 7,
    name: "Sushi",
    desc: "Finest fish and veggies",
    amount: "$59",
    image: img7,
  },
  {
    _id: 8,
    name: "Bread Snacks",
    desc: "Healthy snacks with 3Bs berries, bananas, and bread",
    amount: "$59",
    image: img8,
  },
  {
    _id: 9,
    name: "Kadhi",
    desc: "Finest fish and veggies",
    amount: "$59",
    image: img9,
  },
  {
    _id: 10,
    name: "Sushi",
    desc: "Finest fish and veggies",
    amount: "$59",
    image: img10,
  },
  {
    _id: 11,
    name: "Sushi",
    desc: "Finest fish and veggies",
    amount: "$59",
    image: img11,
  },
];
